
FROM node:18-alpine3.16 AS build-stage

RUN npm i -g typescript

WORKDIR /tmp

COPY package*.json /tmp

RUN npm i

COPY / /tmp

RUN tsc



FROM node:18-alpine3.16 AS prod-stage

WORKDIR /app

COPY --from=build-stage /tmp/package*.json /app

COPY --from=build-stage /tmp/build /app/

RUN npm i --only=prod

ENTRYPOINT node /app/app.js


# docker password
# vg8PgLTn!#L@Xxe

# username 156565